# Functional differences

```{r load_data_func,comment="", echo=FALSE, message=FALSE, warning=FALSE}
load("resources/metagenomics/data_filtered.Rdata")
```

```{r gift_analysis, comment="", message=FALSE, warning=FALSE}
genome_counts_filt <- genome_counts_filt %>%
  column_to_rownames(., "genome") %>%
  filter(rowSums(. != 0, na.rm = TRUE) > 0) %>%
  select_if(~!all(. == 0))%>%
  rownames_to_column(., "genome")

genome_gifts <- genome_gifts[rownames(genome_gifts) %in% genome_counts_filt$genome,]
genome_gifts <- genome_gifts[, colSums(genome_gifts != 0) > 0]
genome_counts_filt <- genome_counts_filt[genome_counts_filt$genome %in% rownames(genome_gifts),]

#Aggregate bundle-level GIFTs into the compound level
GIFTs_elements <- to.elements(genome_gifts,GIFT_db)
GIFTs_elements_filtered <- GIFTs_elements[rownames(GIFTs_elements) %in% genome_counts_filt$genome,]
GIFTs_elements_filtered <- as.data.frame(GIFTs_elements_filtered) %>% 
  select_if(~ !is.numeric(.) || sum(.) != 0)

#Aggregate element-level GIFTs into the function level
GIFTs_functions <- to.functions(GIFTs_elements_filtered,GIFT_db)

#Aggregate function-level GIFTs into overall Biosynthesis, Degradation and Structural GIFTs
GIFTs_domains <- to.domains(GIFTs_functions,GIFT_db)

#Get community-weighed average GIFTs per sample
genome_counts_row <- genome_counts_filt %>%
  mutate_at(vars(-genome),~./sum(.)) %>% 
  column_to_rownames(., "genome") 
# genome_counts_row <- rownames_to_column(genome_counts_row, "genome")
GIFTs_elements_community <- to.community(GIFTs_elements_filtered,genome_counts_row,GIFT_db)
GIFTs_functions_community <- to.community(GIFTs_functions,genome_counts_row,GIFT_db)
GIFTs_domains_community <- to.community(GIFTs_domains,genome_counts_row,GIFT_db)
```

## Functional capacity of the MAGs

```{r GIFTs_elements, comment="", message=FALSE, warning=FALSE, fig.dim = c(20, 20)}
GIFTs_elements %>%
  reshape2::melt() %>%
  dplyr::rename(Genome = Var1, Code_element = Var2, GIFT = value) %>%
  inner_join(GIFT_db,by="Code_element") %>%
  ggplot(., aes(x=Code_element, y=Genome, fill=GIFT, group=Code_function))+
  geom_tile()+
  scale_y_discrete(guide = guide_axis(check.overlap = TRUE))+
  scale_x_discrete(guide = guide_axis(check.overlap = TRUE))+
  scale_fill_gradientn(limits = c(0,1), colours=brewer.pal(7, "YlGnBu"))+
  facet_grid(. ~ Code_function, scales = "free", space = "free")+
  theme_grey(base_size=8)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),strip.text.x = element_text(angle = 90))
```

## MCI

```{r gitfs_bats, message=FALSE, warning=FALSE}

unique_funct_db<- GIFT_db[c(3,4,5)] %>% 
  distinct(Code_function, .keep_all = TRUE)

# 
# deg <- unique_funct_db %>% 
#   filter(Domain=="Degradation")
# 
# existing_columns <- intersect(deg$Code_function, colnames(GIFTs_functions_community))

GIFTs_functions_community %>%
  as.data.frame() %>% 
#  select(all_of(existing_columns)) %>% 
  rowMeans() %>%
  as_tibble(., rownames = "sample") %>%
  left_join(sample_metadata, by = join_by(sample == sample)) %>%
  group_by(Species) %>%
  summarise(MCI = mean(value), sd = sd(value))%>% 
  mutate(MCI_degradation = str_c(round(MCI, 3), "±", round(sd, 3))) %>% 
  column_to_rownames(., "Species") %>% 
  select(MCI_degradation)

MCI <- GIFTs_functions_community %>%
  rowMeans() %>%
  as_tibble(., rownames = "sample") %>%
  left_join(sample_metadata, by = join_by(sample == sample)) 

shapiro.test(MCI$value)
results_aov <- aov(value ~ Species, data=MCI)
summary(results_aov)
```

***Functional differences considering the three species***
```{r commun_wilcox_elem_bats, comment="", message=FALSE, warning=FALSE}
uniqueGIFT_db<- unique(GIFT_db[c(2,4,5,6)]) %>% unite("Function",Function:Element, sep= "_", remove=FALSE)

element_gift <- GIFTs_elements_community %>% 
  as.data.frame() %>% 
  rownames_to_column(., "sample") %>% 
  left_join(., sample_metadata[c(1,2)], by=join_by("sample"=="sample"))
```

***p adjusted***
```{r}
element_gift %>%
    pivot_longer(-c(sample,Species), names_to = "trait", values_to = "value") %>%
    group_by(trait) %>%
  summarise(p_value = summary(aov(value ~ Species))[[1]][["Pr(>F)"]][1]) %>%
  mutate(p_adjust = p.adjust(p_value, method = "BH")) %>%
  filter(p_adjust < 0.05) %>%
  left_join(.,uniqueGIFT_db[c(1,3)],by = join_by(trait == Code_element))
```

***p value***
```{r}
element_gift %>%
    pivot_longer(-c(sample,Species), names_to = "trait", values_to = "value") %>%
    group_by(trait) %>%
  summarise(p_value = summary(aov(value ~ Species))[[1]][["Pr(>F)"]][1]) %>%
  filter(p_value < 0.05) %>%
  left_join(.,uniqueGIFT_db[c(1,3)],by = join_by(trait == Code_element))
```

```{r commun_wilcox_func, comment="", message=FALSE, warning=FALSE}
significant_functional <- element_gift %>%
    pivot_longer(-c(sample,Species), names_to = "trait", values_to = "value") %>%
    group_by(trait) %>%
  summarise(p_value = summary(aov(value ~ Species))[[1]][["Pr(>F)"]][1]) %>%
    filter(p_value < 0.05)%>%
  left_join(.,uniqueGIFT_db[c(1,3)],by = join_by(trait == Code_element))

```
```{r  function_sig, comment="", message=FALSE, warning=FALSE}
function_gift_t <- element_gift  %>% 
  select(-Species)  %>% 
  t() %>%
  row_to_names(row_number = 1) %>%
  as.data.frame() %>%
  mutate_if(is.character, as.numeric)  %>%
  rownames_to_column(., "trait")

function_gift_filt <- subset(function_gift_t, trait %in% significant_functional$trait) %>% 
  t() %>%
  row_to_names(row_number = 1) %>%
  as.data.frame() %>%
  mutate_if(is.character, as.numeric)  %>%
  rownames_to_column(., "sample")%>% 
  left_join(., sample_metadata[c(1,2)], by = join_by(sample == sample))

function_gift_filt %>%
  select(-sample)%>%
  group_by(Species)  %>%
  summarise(across(everything(), mean))%>%
   t() %>%
  row_to_names(row_number = 1) %>%
  as.data.frame() %>%
  mutate_if(is.character, as.numeric)  %>%
  rownames_to_column(., "Code_element")  %>%
  left_join(.,uniqueGIFT_db[c(1,3)],by = join_by(Code_element == Code_element))
```

```{r function_plot, comment="", message=FALSE, warning=FALSE}
function_gift_names <- function_gift_filt%>%
  select(-Species)%>%
   t() %>%
  row_to_names(row_number = 1) %>%
  as.data.frame() %>%
  mutate_if(is.character, as.numeric)  %>%
  rownames_to_column(., "Code_element")  %>%
  left_join(.,uniqueGIFT_db[c(1,4)],by = join_by(Code_element == Code_element))%>%
  select(-Code_element)%>%
  select(Element, everything())%>%
   t()%>%
  row_to_names(row_number = 1) %>%
  as.data.frame() %>%
  mutate_if(is.character, as.numeric)  %>%
  rownames_to_column(., "sample")%>% 
  left_join(., sample_metadata[c(1,2)], by = join_by(sample == sample))

colNames <- names(function_gift_names)[2:19]
for(i in colNames){
  plt <- ggplot(function_gift_names, aes(x=Species, y=.data[[i]], color = Species, fill=Species)) +
    geom_boxplot(alpha = 0.2, outlier.shape = NA, width = 0.3, show.legend = FALSE) +
  geom_jitter(width = 0.1, show.legend = TRUE) +
    scale_color_manual(values=c("#e5bd5b", "#6b7398", "#6b9098"))+
    scale_fill_manual(values=c("#e5bd5b", "#6b7398", "#6b9098"))+
  theme_minimal() +
  theme(
    axis.line = element_line(size = 0.5, linetype = "solid", colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank())
print(plt)
}
```
```{r}
element_gift <- GIFTs_elements_community %>% 
  as.data.frame() %>% 
  rownames_to_column(., "sample") %>% 
  left_join(., sample_metadata[c(1,2)], by = join_by("sample" == "sample"))

uniqueGIFT_db <- unique(GIFT_db[c(2,4,5,6)]) %>% 
  unite("Function", Function:Element, sep = "_", remove = FALSE)

anova_results <- element_gift %>%
  pivot_longer(-c(sample, Species), names_to = "trait", values_to = "value") %>%
  group_by(trait) %>%
  summarise(
    anova_p = summary(aov(value ~ Species))[[1]][["Pr(>F)"]][1]  
  ) %>%
#  mutate(p_adjust_ANOVA = p.adjust(anova_p, method = "BH")) %>%
  filter(anova_p < 0.05)

element_gift %>%
  pivot_longer(-c(sample, Species), names_to = "trait", values_to = "value") %>%
  inner_join(anova_results, by = "trait") %>% 
  group_by(trait) %>%
  summarise(
    tukey_results = list(
      as.data.frame(TukeyHSD(aov(value ~ Species))$Species) |> 
      tibble::rownames_to_column("contrast")
    )
  ) %>%
  unnest(tukey_results) %>% 
 filter(`p adj` < 0.05) %>% 
         left_join(., uniqueGIFT_db[c(1,3)], by = join_by(trait == Code_element)) %>% 
  tt()
```
